### ISSUE TITLE
options inet6 in /etc/resolv.conf cause kafka not to compile

### ISSUE THREAD

**Issue by bf31415** [TrackingSoft/Kafka#12]
I added options inet6 to my resolv.conf to prefer ipv6 resolution over ipv4.  however this breaks kafka-- i see the following compile errors:

Bad arg length for NetAddr::IP::Util::mask4to6, length is 128, should be 32 at /usr/local/lib/perl/5.18.2/NetAddr/IP/Lite.pm line 647.
Compilation failed in require at /usr/local/lib/perl/5.18.2/NetAddr/IP.pm line 8.
BEGIN failed--compilation aborted at /usr/local/lib/perl/5.18.2/NetAddr/IP.pm line 8.
Compilation failed in require at /usr/local/share/perl/5.18.2/Data/Validate/IP.pm line 10.
BEGIN failed--compilation aborted at /usr/local/share/perl/5.18.2/Data/Validate/IP.pm line 10.
Compilation failed in require at /usr/local/share/perl/5.18.2/Kafka/Connection.pm line 41.
BEGIN failed--compilation aborted at /usr/local/share/perl/5.18.2/Kafka/Connection.pm line 41.
Compilation failed in require at ./foo.pl line 22.
BEGIN failed--compilation aborted at ./foo.pl line 22.

**Comment by sezal** [comment]
We don't use NetAddr::IP::Util explicitly, but the problem definitely with this module. Are you able to install it manually?

What's the OS you are trying to install it on?
