### ISSUE TITLE
Invalid test dependencies on IO::File 1.16 and IO::Socket::INET 1.33

### ISSUE THREAD

**Issue by Grinnz** [TrackingSoft/Kafka#13]
Kafka currently has test-requires dependencies on IO::File 1.16 and IO::Socket::INET 1.33, however these versions are not available on CPAN as a stable release, so cannot be installed on perls where these versions are not already core. On perl 5.16.0 and later the core versions of these modules will satisfy the dependency, but on earlier versions they cannot. The dependencies should be lowered to IO::File 1.14 and IO::Socket::INET 1.31 (the versions that were core in 5.10.0 and are available on CPAN) if they are to be sensible for perls before 5.16.0. (Right now older perl versions only pass on cpantesters when the smoker fails to install these modules and then continues to test the module anyway: http://www.cpantesters.org/cpan/report/2199798a-cf12-11e5-a865-d0b4aef69d38)

Example from perl 5.14.4:
``` 
> cpanm IO::Socket::INET@1.33
! Finding IO::Socket::INET (== 1.33) on cpanmetadb failed.
Found IO::Socket::INET 1.31 which doesn't satisfy == 1.33.
```

**Comment by sezal** [comment]
Fixed in 0.9010. Thank you.
