### ISSUE TITLE
Test::More 1.72 ?

### ISSUE THREAD

**Issue by seuf** [TrackingSoft/Kafka#14]
Hi,
I can't install Kafka with cpan, cause the dependency Test::More is not satisfied.

```
Configuring Kafka-0.9010 ... OK
==> Found dependencies: Test::More
Found Test::More 1.302019 which doesn't satisfy 1.72.
! Installing the dependencies failed: Installed version (1.302019) of Test::More is not in range '1.72'
! Bailing out the installation for Kafka-0.9010.
```

I think you should change the version of the required Test::More in your Makefile.PL

**Comment by sezal** [comment]
Could you please give us more details about your platform? Perl version, OS

**Comment by sezal** [comment]
We just released a new version of Kafka module. It should be available on CPAN in couple hours.
Thank you for bug report.
