### ISSUE TITLE
Document unsupported / unimplemented kafka 0.9+ features

### ISSUE THREAD

**Issue by andyfeller** [TrackingSoft/Kafka#16]
The work to date is pretty significant and much appreciated, however I have spent a bit of time trying to understand which Kafka features are unsupported and/or unimplemented and think it'd be worth documenting these potentially with a rough implementation road map.  With [kafka 0.10 released on May 24th 2016](http://www.confluent.io/blog/announcing-apache-kafka-0.10-and-confluent-platform-3.0), this would help users tremendously.

Looking at [Kafka/Internals.pm](https://github.com/TrackingSoft/Kafka/blob/master/lib/Kafka/Internals.pm) and [Apache Kafka protocol](http://kafka.apache.org/protocol.html#protocol_details), it appears only 4 of the 18 API endpoints are implemented (Produce, Fetch, Offset, Metadata) with the bulk of missing endpoints being the new kafka 0.9 consumer API endpoints.

Kafka Protocol API endpoints:
- Produce API (Key: 0)
- Fetch API (Key: 1)
- Offsets API (Key: 2)
- Metadata API (Key: 3)
- LeaderAndIsr API (Key: 4)
- StopReplica API (Key: 5)
- UpdateMetadata API (Key: 6)
- ControlledShutdown API (Key: 7)
- OffsetCommit API (Key: 8)
- OffsetFetch API (Key: 9)
- GroupCoordinator API (Key: 10)
- JoinGroup API (Key: 11)
- Heartbeat API (Key: 12)
- LeaveGroup API (Key: 13)
- SyncGroup API (Key: 14)
- DescribeGroups API (Key: 15)
- ListGroups API (Key: 16)
- SaslHandshake API (Key: 17)
- ApiVersions API (Key: 18)

**Comment by andyfeller** [comment]
It seems some of these limitations are documented on [lib/Kafka.pm](https://github.com/TrackingSoft/Kafka/blob/master/lib/Kafka.pm#L1526), which are easy to overlook, so maybe these should be moved to the README with some updates:
> Producer and Consumer methods only work with one topic and one partition at a time. Also module does not implement the Offset Commit/Fetch API.

**Comment by sezal** [comment]
Thank you for suggestion. We'll try make it more clear in the next release.
