### ISSUE TITLE
Compression error: unable to decompress snappy compressed data

### ISSUE THREAD

**Issue by bf31415** [TrackingSoft/Kafka#18]
I've got a kafka topic where the messages are apparently intermittently uncompressed and compressed.  Using kafkacat, i can verify that there is a mix of compressed and uncompressed messages in the topic but also that the compressed messages are correctly formated as kafkacat is able to properly decompress them.

This is the error i see when attempting a fetch:

Compression error: Unable to decompress snappy compressed data

In looking at the docs I see:

  The main features of the Kafka::Consumer class are:

  Supports Apache Kafka Requests and Responses (FETCH with no compression codec attribute now). Within this module we currently support access to FETCH Request, OFFSETS Request, FETCH Response, OFFSETS Response.

So it looks like the consumer code today does not support fetch with compression.  Is there an ETA when compression support for fetch will be supported?

Thanks

**Comment by sezal** [comment]
It looks like you are using old version of the module.
Could you please confirm the issue with the latest version (http://search.cpan.org/~sgladkov/Kafka-1.001001/lib/Kafka.pm) of the module?

**Comment by bf31415** [comment]
Thanks for the note.   I dug further on this, and there error I'm hitting is in Kafka/Protocol.pm:

                print ("in message_set SNAPPY decompression -- before call to snapp decompress\n");
                #print ("msg to decompress=[%s]\n", $Message->{Value});
                $decompressed = Compress::Snappy::decompress( $Message->{Value} )
                    // _error( $ERROR_COMPRESSION, 'Unable to decompress snappy compressed data' );
                print ("in message_set SNAPPY decompression -- after call to snapp decompress\n");

Apologies for my debug prints.  what's happening is the call to Compress::Snappy::decompress is failing sometimes and so the print post the decompress call isn't executed and I hit my "catch" statement surrounding the fetch () call.   Some background - the kafka topic I'm consuming from has a mix of uncompressed and compressed msgs.   I think at times the fetch is getting multiple messages where some are compressed and some are not.  I don't know if that's explicitly supported in the Kafka code to process a mix is compressed and not compressed message received in a single message set.

I don't understand the structure of what comes back from the low level fetch to determine if the issue is with how Kafka is pulling apart each message in the set or if there's something broken with the Compress::Snappy code.

Note that if I watch the topic with kafkacat, it's able to decode all the messages- so I believe the producer/kafka is generating correct messages.  I'd be happy to instrument the Kafka code further if you can give me some direction on what information would be useful to you to debug the issue.

Thanks
Brian

**Comment by sezal** [comment]
Brian,

Our Kafka module supports mixed messages. You don't expected to use Compress::Snappy explicitly to decompress data. Kafka module supposed to decompress messages transparently.

Please see special handling of Snappy compressed messages in https://github.com/TrackingSoft/Kafka/blob/master/lib/Kafka/Protocol.pm#L1184
It may be a reason why your attempts to use Compress::Snappy directly fails.

**Comment by bf31415** [comment]
I'm seeing the failure in this line:

https://github.com/TrackingSoft/Kafka/blob/master/lib/Kafka/Protocol.pm#L1194

Notice that the error message I reported is the one show in the line 1195 (eg "unable to decompress snappy compressed data").

It's not clear to me if the issue is in the Kafka code which is walking through the MessageSet and processing each message sequentially  (lines 1151-1173) or if the issue is in the Compress:Snappy::decompress code itself.

What info would be useful for you to see to debug this?

Thanks
Brian

**Comment by sezal** [comment]
Could you please try setting
$ENV{PERL_KAFKA_DEBUG} = '2';
and provide output.

It would be nice to know versions of Compress::Snappy, Kafka.pm and Kafka itself.
Thank you.

**Comment by bf31415** [comment]
I'd need to setup a dummy topic and data and see if I can recreate the issue.   In the mean time, below is the hex output of the beginning of one of the received SNAPPY compressed messages (eg $Message->{Value})

od --endian=big -x ./foo | head -6
0000000 8253 4e41 5050 5900 0000 0001 0000 0001
0000020 0000 18a1 8080 0200 0001 0128 12ba 1b00
0000040 0003 47bc c39c 1f01 0ff0 e800 2032 3230
0000060 3637 3465 3763 3065 6165 6261 3464 3630
0000100 3338 6364 3339 3330 3065 3534 3300 0003
0000120 1956 3a20 312e 330a 435f 4841 5348 5f49

The first 20 bytes in yellow are contain the "\x82SNAPPY\00" and xerial header.  These yellow bytes are the 20 bytes that are removed from $Message->{Value} before attempting to decode the message via Compress::Snappy::decompress.

If I send the entire object (including those 20 yellow bytes) to snzip (snappy-java/xerial) it decodes properly.

So it looks like the perl Kafka is pulling the messages apart correctly.  I don't understand enough about what needs to be passed to the Compress::Snappy::decompress if the issue is more or fewer bytes should be removed before being passed to decompress or if Compress:Snappy::decompress.

If I take the entire object and feed it into Compress::Snappy::decompress outside of Kafka, I get undef back.

Is the issue that the above snappy compression format isn't supported by Compress::Snappy::decompress?

Brian

**Comment by sezal** [comment]
Compress::Snappy uses Google Snappy code which doesn't seem to support "magic" header. That's why we included implicit removal of that header in our code. Other Snappy implementations have similar workaround. See
https://github.com/xerial/snappy-java/issues/142
https://github.com/kubo/snzip/blob/master/snappy-java-format.c

**Comment by als1** [comment]
Hey guys, Was there a resolution to this? As I understand from the last 2 messages, there was a workaround built into the package . But I am still getting the "Unable to decompress snappy compressed data" from Kafka::Consumer when I use snappy compression. I am using the most recent version of both Kafka (1.001013) and Compress::Snappy (0.24), with kafka 0.9.

Any suggestions on how to work around this problem? I tried gzip as well, but the compression overhead is a lot higher. By the way, you might want to switch to Gzip::Faster, which is quite a bit faster than IO::Compress::Gzip (about 20% faster in my testing, and there are more stats in the docs for Gzip::Faster). But still Compress::Snappy is much lower overhead (though not as good compression).

Let me know if you have any suggestions. Thanks!

**Comment by asolovey** [comment]
> There was a workaround built into the package . But I am still getting the "Unable to decompress snappy compressed data" from Kafka::Consumer when I use snappy compression. I am using the most recent version of both Kafka (1.001013) and Compress::Snappy (0.24), with kafka 0.9.

Can you decompress the same message using other implementations of consumer (e.g. Java or Python)? If the problem happens with our module only, I'd like to see an example of compressed message which causes the problem.

**Comment by als1** [comment]
Sorry, haven't had a chance to test the snappy compression with python yet, but I will test it early next week.

**Comment by filimonov** [comment]
Probably caused by lack of support of decompression of multiframe xerial snappy-java format.
Pull request #39 fixes that.

**Comment by filimonov** [comment]
Please check version 1.07
