### ISSUE TITLE
Uses List::Util::all from v1.33 - declares dependency on v1.19

### ISSUE THREAD

**Issue by adsj** [TrackingSoft/Kafka#19]
The dependency declaration: https://github.com/TrackingSoft/Kafka/blob/master/META.json#L48
says that List::Util 1.19 is needed, but the code uses List::Util::all, e.g.: https://metacpan.org/source/SGLADKOV/Kafka-1.001001/lib/Kafka/Connection.pm#L44
all() was added to List::Util in 1.33: https://metacpan.org/pod/List::Util#all
I guess the dependency should be bumped to 1.33?

(I am trying to package Kafka for Ubuntu 14.04, Perl 5.18.2, which is why I bumped into this.)

**Comment by vladm** [comment]
Good catch, we'll fix it. Thank you.

**Comment by adsj** [comment]
Would it be possible to make Kafka run on Perl 5.18.2?

**Comment by adsj** [comment]
Ah, @dk just pointed out (see pull request #20) that List::Util::all() is not used anywhere in the code, so the best solution is to simply remove the 'all' from the 'use'-line:

 *  https://metacpan.org/source/SGLADKOV/Kafka-1.001001/lib/Kafka/Connection.pm#L44

(i.e. L45).

The tests depend on Test::TCP >=2.08, by the way (can_bind was introduced then), I think.

With those two things handled, I can install Kafka on Perl 5.18.2.

**Comment by sezal** [comment]
fixed in 1.001011
