### ISSUE TITLE
Gzip::Faster might get some compression perf improvement

### ISSUE THREAD

**Issue by als1** [TrackingSoft/Kafka#24]
I tried using gzip compression (since snappy didn't work), but there was a noticeable perf hit when I turned on compression. IO::Compress::Gzip is known to be slow. Gzip::Faster is faster (see docs, and it was about 20% faster in my quick testing on our data). Would it be possible to switch to the latter to get a bit of gzip perf improvement?

**Comment by asolovey** [comment]
I can try switching to Gzip::Fast and see if any tests fail. The problem with Snappy may be caused by workaround for non-standard header produced by java-snappy. We need to spend some time looking into that again.

**Comment by asolovey** [comment]
Fixed in 7fa310a2116fbe5a4ed061c55bf14c1cd00babe9
