### ISSUE TITLE
test 43 failing ?

### ISSUE THREAD

**Issue by dams** [TrackingSoft/Kafka#26]
Hi,

When I run test t/43_competition.t against master, I get this kind of output:

```
t/43_competition.t (Wstat: 0 Tests: 333 Failed: 12)
  Failed tests:  3-5, 7, 9, 11, 13, 15, 17, 19-21
  Parse errors: Tests out of sequence.  Found (5) but expected (27)
                Tests out of sequence.  Found (27) but expected (28)
                Tests out of sequence.  Found (13) but expected (29)
                Tests out of sequence.  Found (17) but expected (30)
                Tests out of sequence.  Found (11) but expected (31)
```

Is this issue specific to my setup? Is it something I should worry about ? Thanks

**Comment by asolovey** [comment]
Don't worry. This test fails constantly on travis CI for yet unknown reasons (hard to find the cause as there is no direct access to the running travis build). I suspect there's something odd with timeouts there, but I'm not sure.
We use Jenkins locally and there is no such failures. I'm tried to fix this test for travis but no luck so far. Will try again ;)

**Comment by dams** [comment]
Thanks. For what it's worth, I can reproduce the failure on my laptop (MacOS X with perl 5.25)
