### ISSUE TITLE
v. 1.02 may be broken with kafka 0.9

### ISSUE THREAD

**Issue by als1** [TrackingSoft/Kafka#29]
I have a cluster that's running Confluent 2.0.0, which I think is kafka 0.9.0.0. I tried the latest perl Kafka package (v. 1.02) to see if it fixes a timeout issue I reported earlier. However, the connector seems to have broken in this release. The error I get is:

Invalid argument: Server 'x.x.x.x:9092' is not connected (error code: -1000)

Not sure if this makes a difference, but this cluster has 3 hosts, so we use Kafka::Connection with a broker_list (not a single host). The cluster it's reporting in the error is the 2nd on the list (again, not sure if that makes a difference).

The package works fine with another cluster that's running Confluent 3.0.0 (which I think is kafka 0.10.0.0).

I am wondering if anyone else has run into this? Is kafka 0.9 still supported (the doc claims it is)? Was this release of the package tested with kafka 0.9? Let me know if I can provide more detail. Thanks.

**Comment by asolovey** [comment]
There was a major change to support multiple API protocol versions. It is possible that there is some incompatibility with 0.9. Please try adding

   `dont_load_supported_api_versions => 1`

to Kafka::Connection constructor parameters and see if that helps.

**Comment by als1** [comment]
Yes, that fixed it.

**Comment by asolovey** [comment]
Fixed in 1.03. Using dont_load_supported_api_versions => 1 for 0.9 is recommended to avoid unnecessary attempts to get API versions.
