### ISSUE TITLE
Security Protocal Support

### ISSUE THREAD

**Issue by kahshin** [TrackingSoft/Kafka#31]
Does Kafka pm support Security Protocol for example "SASL_PLAINTEXT"?

Also, I encounter error "could not get metadata" and not sure what's the real issue. How do I find out more?

**Comment by asolovey** [comment]
> Does Kafka pm support Security Protocol for example "SASL_PLAINTEXT"?

Unfortunately, no.

> Also, I encounter error "could not get metadata" and not sure what's the real issue. How do I find out more?

The real issue may be a failed broker connection or some protocol handling error on our side. You can try enabling debug output:
```
export PERL_KAFKA_DEBUG=1
```
and see if there is some useful info.
