### ISSUE TITLE
Why is Solaris explicitly unsupported? 

### ISSUE THREAD

**Issue by gmarler** [TrackingSoft/Kafka#4]
I notice Solaris is explicitly listed  in Makefile.PL as being unsupported,  but don't see any reason that should be so.  Can you explain why?

**Comment by sezal** [comment]
As far as I remember some builds on Solaris failed in the past. We didn't have resources to test/support the OS we don't plan to use for own needs. I believe it was easier just to exclude this OS from supported list.
Were you able to install the module manually (by adjusting Makefile.PL) on Solaris? Did all tests passed successfully? What Solaris version you tested on?

**Comment by gmarler** [comment]
I'll put it through it's paces and let you know.  I know it built without issue on Solaris 11.2 x86, but I want to try it on Solaris 11.2 SPARC as well, which is primarily where we would use it.
