### ISSUE TITLE
producer timeout default

### ISSUE THREAD

**Issue by hv-pirum** [TrackingSoft/Kafka#43]
In `Kafka::Producer->new`, I'd like to propose that it would make slightly more sense to set the response timeout based on:
- the value of the `Timeout` parameter, if supplied;
- else the timeout set on the `Kafka::Connection` object if that is supplied;
- else the default `$REQUEST_TIMEOUT`.

We were trying to diagnose some failures what turned out to be a slow VM, it caused some confusion that the Connection timeout was used for everything except this one case.

It's also a bit confusing that the parameter is `timeout` for Connection and `Timeout` for Producer, but I guess it may be hard to change that now.

**Comment by asolovey** [comment]
Fixed in 2c8c370
