### ISSUE TITLE
unpack syntax error

### ISSUE THREAD

**Issue by jpfrigeriogithub** [TrackingSoft/Kafka#49]
I just downloaded v 1.07 and all deps.  
tried to setup a consumer, connection worked, but as soon as I try to access offsets or messages or anything, it throws this exception:

'/' must follow a numeric type in unpack at /usr/local/share/perl5/Kafka/Protocol.pm line 1387

perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

**Comment by asolovey** [comment]
I do not have perl 5.16 installed and cannot check this, but I believe this used to be a misleading error message for truncated strings, like when you try to `unpack('v/A*', 'a')`, so it may be network issue reported incorrectly.
Could you try some more recent perl version and see if the same error happens there? 

Also, what is the version of Kafka server you're connecting to?
