### ISSUE TITLE
Implement Offset Commit/Fetch API

### ISSUE THREAD

**Issue by lukec** [TrackingSoft/Kafka#5]
Hello,

I'm very keen to use the new offset commit/fetch API features to avoid needing to store consumer offsets in another system.

Is there anyone taking this work on, or with advice on how to proceed?

Best,
Luke

**Comment by sezal** [comment]
We are planning to work on offset api as Kafka team will get closer to releasing version 0.8.3. In the meantime you are welcome to submit your implementation via pull request

**Comment by asolovey** [comment]
As of 1.06, we have basic support for offset commit/fetch (thanks to @dams).
