### ISSUE TITLE
ipv6 only perl kafka issue

### ISSUE THREAD

**Issue by bf228** [TrackingSoft/Kafka#7]
I've got a v6 only kafka cluster (the brokers only have v6 addresses).  I've run into two issues with the perl kafka code accessing this cluster.  First, it looks like there's an expectation that the host value passed in a Connection->new() call needs to be the ipv6 address as opposed to a fqdn (which resolves only to a v6 address).  Second, in my kafka server.config I've found that i need to specific the ipv6 address as opposed to an fqdn for "advertised.host.name".  It appears the issue i'm running into with the perl kafka code is related to issues in _gethostbyname in IO.pm.  It appears the existing logic there (and with _get_family) defaults to assume a fqdn is a v4 AF.   I've modified _gethostbyname to allow for both v4 and v6 fqdn resolution which seems to solve the above issues.  Code is below. 

sub _gethostbyname {
    my ( $self, $name ) = @_;

    # prefer v6 resolution.  if no v6 address then try v4
    my ( $err, @addrs ) = Socket::getaddrinfo( $name, 0, { 'protocol' => undef, 'family' => Socket::AF_INET6 } );

    if (! $err) {
        $self->{af} = AF_INET6;
        $self->{pf} = PF_INET6;
    } else {
        ($err, @addrs ) = Socket::getaddrinfo( $name, 0, { 'protocol' => undef, 'family' => Socket::AF_INET } );
        $self->{af} = AF_INET;
        $self->{pf} = PF_INET;
    }

    for my $addr (@addrs) {
       my ( $err, $ipaddr ) = Socket::getnameinfo( $addr->{addr}, Socket::NI_NUMERICHOST );
       if ($err) { next }
       $self->{ip} = $ipaddr;
       return $self->{ip};
    }

    $self->{ip} = '';
    return $self->{ip};
}

**Comment by sezal** [comment]
We have just release a new version of Kafka module. There is a new "ip_version" option that should be helpful in your case.
